### ISSUE TITLE
choosewin: Vim(let):E117: Unknown function: uniq

### ISSUE THREAD

**Issue by yuta-masano** [t9md/vim-choosewin#10]
Hi, thanks for your awesome plugin!

I found a slight error that says "choosewin: Vim(let):E117: Unknown function: uniq", when starting to display window labels.
I'm not sure about vim script. But the following modify seems to work well.

autoload/choosewin/overlay.vim|161|
\- let render_lines = uniq(b:choosewin.render_lines)
\+ let render_lines = s:_.uniq(b:choosewin.render_lines)

Please confirm it.

**Comment by t9md** [comment]
Thanks reporting.
Sorry about that. I didn't noticed since I use newer version of Vim thats have native uniq() function.
What vim version are you using and overlay feature work without problem?
Hope your feedback.

**Comment by yuta-masano** [comment]
Here is my environmet.
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:34)
適用済パッチ: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge 版 without GUI.  機能の一覧 有効(+)/無効(-)
(snip)
```

 And, my vim-choosewin settings.
```
nmap , <Plug>(choosewin)
let g:choosewin_overlay_enable = 1
let g:choosewin_overlay_clear_multibyte = 1
let g:choosewin_color_overlay = {
            \   'gui': ['DodgerBlue3', 'DodgerBlue3' ],
            \   'cterm': [ 25, 25 ]
            \   }
let g:choosewin_color_overlay_current = {
            \   'gui': ['firebrick1', 'firebrick1' ],
            \   'cterm': [ 124, 124 ]
            \   }
let g:choosewin_blink_on_land      = 0 "
let g:choosewin_statusline_replace = 0 "
let g:choosewin_tabline_replace    = 0 "
let g:choosewin_keymap = {
            \ ',':     'previous',
            \ }
```
As mentioned above, I am not familiar with vim scripts, sory. I do not know whether my modification is valid or not.
So, revert my arbitrary modification, and I would like to organize my error situation.
* When I set let g:choosewin_overlay_enable = 1, and call choosewin, Unknown function error was reppoted.
* When I set let g:choosewin_overlay_enable = 0, Unknown function error was not reppoted.

If you need more information, feel free to comment. I will lend my hand as much as possible.

**Comment by t9md** [comment]
I've already fixed for uniq() bug, please check latest code.
thanks

**Comment by yuta-masano** [comment]
:thumbsup:
It works fine! Thanks!
