### ISSUE TITLE
Animated GIF in README is broken

### ISSUE THREAD

**Issue by KevinSjoberg** [t9md/vim-choosewin#17]
The animated GIF used in the `README` is broken. Is there a replacement that can be used? Maybe the GIF from your [website](http://d.hatena.ne.jp/t9md/)?

**Comment by t9md** [comment]
Sorry i use wrong gif for above commit. Will fix again.

**Comment by t9md** [comment]
I will fix by myself when i back to home.

**Comment by KevinSjoberg** [comment]
Okay, thanks a lot! :+1:
