### ISSUE TITLE
Not working on vim 7.2

### ISSUE THREAD

**Issue by emaniacs** [t9md/vim-choosewin#21]
Hi

Iam using this plugin on vim 7.2, but not working, i got error like this..

_choosewin: Vim(call):E355: Unknown option: conceallevel_

![error image](http://imgur.com/s4ztsoI.png)
![vim version](http://imgur.com/ucfpbVR.png)

**Comment by tao12345666333** [comment]
The `conceallevel` is available when compiled with the `+conceal` . You can fix it by recompile your Vim.

**Comment by emaniacs** [comment]
Sorry i forgot this.
Thanks for the advice. :)
