### ISSUE TITLE
Integration with status line plugins

### ISSUE THREAD

**Issue by adelarsq** [t9md/vim-choosewin#24]
Is it possible to do some kind of integration with status line plugins (powerline, vim-airline, lightline, etc)? So the jump character are always shown.

**Comment by mwgkgk** [comment]
I made a simple function to solve this from the outside. Assuming `g:choosewin_label` is set (to anything), like this:
```
let g:choosewin_label='ADFJKLGHQWERUIO'
```
we can then define a function, like this:
```
function! WinLabel()
    let n = winnr() - 1
    return g:choosewin_label[n:n]
endfunction
```
and  use it in the `&statusline`, like this:
```
${WinLabel()}
```

**Comment by adelarsq** [comment]
Nice! Thanks @mwgkgk. I did a little change on the function:

```vim
function! WinLabel()
     let n = winnr() - 1
     return g:choosewin_label[n]
endfunction
```

And a map for tab on normal mode:

```
nmap <tab> <Plug>(choosewin)
```

**Comment by mwgkgk** [comment]
Dang, I've spent some time googling on how to get character at index in vimscript without trying the most obvious thing. :D
