### ISSUE TITLE
Neovim 0.1.2: Overlay and other options stopped working

### ISSUE THREAD

**Issue by rafi** [t9md/vim-choosewin#26]
Since Neovim v0.1.2, overlay and other options stopped working. Seems that commit [79a6983c](https://github.com/neovim/neovim/commit/79a6983c0c40c5f4ad62550c0b43ed100e862a2e) is the fault.

**Comment by t9md** [comment]
Could you check with current HEAD of repo? It shoud be fixed.

**Comment by rafi** [comment]
Fixed, thank you!
