### ISSUE TITLE
Neovim: Setting termguicolors on init breaks overlay

### ISSUE THREAD

**Issue by rafi** [t9md/vim-choosewin#29]
Sorry to bug you again about this, I use this plugin a lot and think it's lovely.

Neovim [v0.1.4-acc5d08b](https://github.com/neovim/neovim/commit/acc5d08b371c9521d63aa4a37cce9ffab451d21d) introduces the `termguicolors` setting. In the terminal, using it on _startup_, makes vim-choosewin's overlay and other options to stop working.

**Comment by t9md** [comment]
Last uear I switched to Atom editor and I haven't tried nvim yet.
So I want someone maintain this plugin or make PR to fix this.
Sorry!

**Comment by t9md** [comment]
Thanks again!
