### ISSUE TITLE
Option to display numbers instead of letters

### ISSUE THREAD

**Issue by charliesbox** [t9md/vim-choosewin#31]
It would be easier to move between windows by using numbers 👍

**Comment by charliesbox** [comment]
I just saw that this could be achieve by `let g:choosewin_label = '123456789'`

however, when I pressed `1`, it doesn't work. But it does with the other numbers.

**Comment by charliesbox** [comment]
In case any other person found this issue :)

All you need to do is invert tabs and windows properties

```let g:choosewin_label = '123456789'```
```let g:choosewin_tablabel = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'```

**Comment by t9md** [comment]
Yes, CAUTIONED in help.
https://github.com/t9md/vim-choosewin/blob/master/doc/choosewin.txt#L129-L130

You can also set this empty `let g:choosewin_tablabel = ''`

**Comment by charliesbox** [comment]
Good to know! thanks @t9md !
