### ISSUE TITLE
Option to toggle between windows

### ISSUE THREAD

**Issue by alexdreptu** [t9md/vim-choosewin#36]
Please provide an option to toggle windows when there are only two open.

**Comment by t9md** [comment]
Focus to previous(`-`) is not what you want?

**Comment by alexdreptu** [comment]
What I was thinking was, when there are only two windows open and you press the keys mapped to ```choosewin```, to toggle between them instead of the hints to appear, like [ace-windows](https://github.com/abo-abo/ace-window) does it in emacs. But now that I'm thinking about it, It doesn't sound like a good idea implemented this way for ```vim-choosewin``` because that would mean to auto-select the other window and return immediately not letting the user choose other actions while in ```choose``` mode. The ```-``` will do, didn't noticed it in the docs.
