### ISSUE TITLE
Ignore Filetype By Hook Doesn't Work

### ISSUE THREAD

**Issue by weilbith** [t9md/vim-choosewin#41]
I copied the  `[Example]` instructions from the documentation at `choosewin-hook_point`. For completion I copy it here:

```vim
let s:ignore_filtype = ["unite", "vimfiler", "vimshell", "nerdtree"]

let g:choosewin_hook = {}
function! g:choosewin_hook.filter_window(winnums)
   return filter(a:winnums,
	\ 'index(s:ignore_filtype,
	\   getwinvar(v:val, "&filetype")) == -1' )
endfunction
```

Unfortunately this does not work for me. Instead of just resource my runtime configuration, I spawn a complete new _Vim_ instance and try it out. I opened a _NerdTree_ window window first and than called `:ChooseWin`. The _NerdTree_ window still get labeled.

**Comment by t9md** [comment]
You at least enable hook by `g:choosewin_hook_enable` var.
But it seems still broken. I haven't used this feature for a very long time.
And I'm not active Vim user now. Maybe this is bug, but this feature is planned to be deleted as you seen in comment in help.txt.

If you really need this feature, please send PR.

**Comment by weilbith** [comment]
Okay, thanks for the quick response.
