### ISSUE TITLE
NERDTree Choosewin Plugin

### ISSUE THREAD

**Issue by weilbith** [t9md/vim-choosewin#43]
Hey!
I love your plugin and I wrote a really simple [NERDTree](https://github.com/scrooloose/nerdtree) extenstion which use this to open files into a selected window. In fact having this plugin installed in parallel is the advanced scenario of this extension.
Maybe you like to reference this in your description, if you like. :v:

**Comment by t9md** [comment]
Great. I can accept PR for doc modification if you like(since I myself isn't actively maintaining this plugin, I basically check and merge PRs).
