### ISSUE TITLE
Possible to have mapping to go to last window?

### ISSUE THREAD

**Issue by collinpeters** [t9md/vim-choosewin#8]
I'm wondering if there is a mapping where you can go to your last window. So say I have numerous splits in a complex layout and I'm going back and forth between B and D.  Would it possible to have a mapping that goes to the last active window?

**Comment by t9md** [comment]
OK. I think its useful. will try, but I'm not actively using vim recently, need time to develop. Please wait a week or so.

**Comment by t9md** [comment]
you can now jump to previous window of previous tab with keymap `-` by default.

**Comment by collinpeters** [comment]
Awesome!!! Works great.
